### ISSUE TITLE
Transaction fee doubt

### ISSUE THREAD

**Issue by heeropunjabi** [MoralisWeb3/plugindocs#6]
Hi Team,
 first of all thanks a lot for the wonderful job done on the moralis side.

while using 1inch plugin using moralis library, I was in doubt, 

are we charging 1% transaction fees for each swap that is happening through you guys or is it the transaction fees of the 1inch.

Since as per my understanding 1inch isn't charging any transaction fees for the swap.

can you guys please help me out before my company takes the decision of using this plugin?

TIA.

**Comment by ivan-liljeqvist** [comment]
Hi sorry for late reply, for fast replies please post here: https://forum.moralis.io/ we monitor that forum all the time
The 1% is our fee
